setting:
  #force2D: true
  #force2Ddimension: 0
  minimumROIDimensions: 2

imageType:
  Original: {}
  Wavelet: {}
  LoG:
    sigma: [1.0, 2.0, 3.0, 4.0, 5.0]  # If you include sigma values >5, remember to also increase the padDistance.
  Square: {}
  SquareRoot: {}
  Logarithm: {}
  Exponential: {}
  Gradient: {}
  LBP2D: {}
  LBP3D: {}
  
  